language: ruby
rvm:
- 2.0.0-p353
before_install:
- gem install bundler
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- bundle exec rake db:create:all
- bundle exec rake db:migrate
- bundle exec rake db:test:prepare
script:
- bundle exec rake cucumber
- bundle exec rake spec
deploy:
  provider: heroku
  api_key:
    secure: "ECgJzJozafPN6dlyzkDQGLUDsTVTLRCWou31YjJB5QnaJ5HNB7qfjlz++ZZ70apjmDBUaHZ7gTyYVqOW6orcbbrTCqgkenW7UcuSuWI9WJvgobakcrAqwP+dAmBNT+wOg55Q6R8+eWPNfv4zehvw4Xj1yLFNdjeYBce6vP5zF6k="
#  app:
#    develop: websiteone-develop
#    master: websiteone-production
  run: "rake db:migrate"
