language: ruby
rvm:
- 2.0.0-p353
before_install:
- gem install bundler
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- bundle exec rake db:create:all
- bundle exec rake db:migrate
- bundle exec rake db:test:prepare
script:
- bundle exec rake cucumber
- bundle exec rake spec
deploy:
  provider: heroku
  api_key:
    secure: ddLEdtLEZyRxafU6TbLjTrrwTfvB24wd3v/bo3PG9VdmM334GNZh7O8WWG8ez8zs9SUPS4A5b7EgLFIVjSizltkYtAJW38NtREpRhjaH07Wm4lHkCZVUpafiSgt4FH21VsDi4O/J/5/2Tb/c/QnrgCpS6yIxhfmq8bKdLg5mxoA=
  run: rake db:migrate
